spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:oracle:thin:@192.168.0.86:1521/ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: DEV
    password: "1234"

file:
  upload:
    path: /dev/upload
