spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:oracle:thin:@//192.168.0.119:1521/ORCLPDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: devuser
    password: dev1234

  data:
    redis:
      enabled: false
      host: localhost
      port: 6379

jwt:
  secret: YQ6hz544Fcd0a1AqPDJ8YGnFVONempMY1rhfMuSG910=
  access-expiration: 7200000        # 2시간
  refresh-expiration: 2592000000    # 30일

file:
  upload:
    path: /app/upload

cors:
  allowed-origins: "*"
